# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks: []
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    - -w -s
    - -X github.com/cloudfoundry/bosh-cli/cmd.VersionLabel={{.Version}}
archives: []
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
