project_name: bosh-cli

builds:
  -
    &template
    id: binary
    binary: bosh-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X github.com/cloudfoundry/bosh-cli/cmd.VersionLabel={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - id: archives
    builds:
      - binary
    format: binary
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: orange-cloudfoundry
    name: bosh-cli
  prerelease: auto
  name_template: '{{.Tag}}'
