---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-garden
    tag: 'latest'

inputs:
- name: bosh-cli
  path: gopath/src/github.com/cloudfoundry/bosh-cli
- name: bosh-warden-cpi-release
  path: cpi-release
- name: bosh-warden-stemcell-xenial
  path: stemcell

run:
  path: gopath/src/github.com/cloudfoundry/bosh-cli/ci/tasks/test-acceptance.sh
